version: '3'

services:
  database:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test!
      MYSQL_DATABASE: test
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
volumes:
  mysql_data: ~